FROM php:8.1-apache

# Instala dependencias necesarias y la extensión mysqli
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    && docker-php-ext-install zip mysqli

# Instala Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copia el código fuente
COPY ./src /var/www/html

# Instala dompdf
WORKDIR /var/www/html
RUN composer require dompdf/dompdf
